spring:
  application:
    name: "dumMoney"

  datasource:
    # [중요 1] RDS 엔드포인트와 DB이름 입력
    # 형식: jdbc:mysql://dumdb.cp0uooomq0t6.ap-northeast-2.rds.amazonaws.com:3306/[데이터베이스이름]?옵션들...
    url: jdbc:mysql://dumdb.cp0uooomq0t6.ap-northeast-2.rds.amazonaws.com:3306/dumdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true

    # [중요 2] RDS 만들 때 설정한 아이디/비번
    username: admin  # 보통 admin 또는 adminuser
    password: dummoney

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 처음엔 테이블이 없으니 update로 설정 (자동 생성됨)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # MySQL 방언 설정 (필수)
        dialect: org.hibernate.dialect.MySQL8Dialect

# Gemini 키는 그대로 유지
gemini:
  api:
    key: AIzaSyBQzDPgWkVYzBc-ctNyip2nVTVWT9OVAgY